language: node_js
node_js:
  - 8
  - 9
  - lts/*
  - node
os:
  - linux
  - osx
matrix:
  include:
  - os: linux
    dist: xenial
  - os: osx
    osx_image: xcode10.1
cache:
  directories:
    - node_modules
#after_success:
#  - npm run examples
#  - npm run out