language: node_js

matrix:
  include:
  - os: linux
    dist: xenial
    node_js:
    - 8
    - 9
    - lts/*
    - node
  - os: osx
    osx_image: xcode10.1
    node_js:
    - 8
    - 9
    - lts/*
    - node
cache:
  directories:
    - node_modules
#after_success:
#  - npm run examples
#  - npm run out